#{% set version = "3.2.1" %}
{% set version = "0.1.0" %}

package:
    name: dftd3
    version: {{ version }}

source:
    path: ../..

build:
    number: 0
#    number: 2                                            # [linux]
#    number: 1                                            # [osx]
#    number: 0                                            # [win]
    binary_relocation: true
    ignore_run_exports:
        # unused libraries
        - libgcc-ng                                      # [linux]
        - libgfortran-ng                                 # [linux]

requirements:
    build:
        - {{ compiler('fortran') }}
        - cmake >=3.3

test:
    commands:
        # Verify executable
        - test -f $PREFIX/bin/dftd3
        - $PREFIX/bin/dftd3 -h
        - $PREFIX/bin/dftd3 -version
        # Inspect linkage
        - ldd -r -u $PREFIX/bin/dftd3                    # [linux]
        - otool -L $PREFIX/bin/dftd3                     # [osx]
        - conda inspect linkages --show-files --groupby=dependency dftd3
        - conda inspect objects -p $PREFIX $PKG_NAME     # [osx]

about:
    home: http://www.thch.uni-bonn.de/tc/index.php?section=downloads&subsection=DFT-D3&lang=english
    # dev_url:
    doc_url: https://www.chemie.uni-bonn.de/pctc/mulliken-center/software/dft-d3/man.pdf
    # doc_source_url:
    license: GPL-1.0+
    # license_url:
    license_file: LICENSE
    license_family: GPL
    summary: "S. Grimme's dispersion correction for DFT, Hartree--Fock, and semi-empirical quantum chemical methods"
    # description: >

#######


#{% set data = load_setup_py_data(setup_file='conda/_conda_vers.py') %}
#
#package:
#  name: psi4
#  version: {{ data.get('version') }}
#
#source:
#  path: ../..
#
#requirements:
#  run:
#    - intel-openmp={{ MKL_VERSION }}
#    - mkl={{ MKL_VERSION }}
#    - networkx
#    - numpy
#    - pytest
#    - python={{ PY_VER }}
#    - qcelemental
#    - qcengine
#    - msgpack-python
#    - gau2grid
#    - libint2
#    - libxc
#
#build:
#  string: py{{ environ['PY_VER'].replace('.', '') }}_{{ 'debug' if environ['CMAKE_BUILD_TYPE'] == 'Debug' else '0' }}
#  script:
#    - md {{ PREFIX }}\Scripts
#    - copy /y {{ INSTALL_DIR }}\bin\psi4 {{ PREFIX }}\Scripts
#    - echo __pycache__ > exclude.txt
#    - xcopy /f /i /s /exclude:exclude.txt {{ INSTALL_DIR }}\lib\psi4 {{ SP_DIR }}\psi4
#    - xcopy /f /i /s {{ INSTALL_DIR }}\share\psi4\basis       {{ PREFIX }}\Lib\share\psi4\basis
#    - xcopy /f /i /s {{ INSTALL_DIR }}\share\psi4\plugin      {{ PREFIX }}\Lib\share\psi4\plugin
#    - xcopy /f /i /s {{ INSTALL_DIR }}\share\psi4\quadratures {{ PREFIX }}\Lib\share\psi4\quadratures
#    {% if environ['CMAKE_BUILD_TYPE'] == 'Debug' %}
#    - copy /y {{ SYSTEMROOT }}\System32\msvcp140d.dll     {{ PREFIX }}
#    - copy /y {{ SYSTEMROOT }}\System32\vcomp140d.dll     {{ PREFIX }}
#    - copy /y {{ SYSTEMROOT }}\System32\vcruntime140d.dll {{ PREFIX }}
#    - copy /y {{ SYSTEMROOT }}\System32\ucrtbased.dll     {{ PREFIX }}
#    {% endif %}
#
#test:
#  commands:
#    - python -c "import psi4; assert psi4.test('quick') == 0"
#    - psi4 --test quick
#(py39) psilocaluser@bash:psinet:/psi/gits/hrw-py39/objdir512: (saptd) cat ../conda/win/meta.yaml 

